function [wndspeed_1_05,...
          wndspeed_2_05,...
          wndspeed_3_05,...
          wndspeed_4_05,...
          wndspeed_5_05,...
          wndspeed_6_05,...
          wndspeed_7_05,...
          wndspeed_8_05,...
          wndspeed_9_05,...
          wndspeed_10_05,...
          wndspeed_11_05,...
          wndspeed_12_05,...
          wndspeed_1_06,...
          wndspeed_2_06,...
          wndspeed_3_06,...
          wndspeed_4_06,...
          wndspeed_5_06,...
          wndspeed_6_06,...
          wndspeed_7_06,...
          wndspeed_8_06,...
          wndspeed_9_06,...
          wndspeed_10_06,...
          wndspeed_11_06,...
          wndspeed_12_06,...
          wndspeed_1_07,...
          wndspeed_2_07,...
          wndspeed_3_07,...
          wndspeed_4_07,...
          wndspeed_5_07,...
          wndspeed_6_07,...
          wndspeed_7_07,...
          wndspeed_8_07,...
          wndspeed_9_07,...
          wndspeed_10_07,...
          wndspeed_11_07,...
          wndspeed_12_07,...
          wndspeed_1_08,...
          wndspeed_2_08,...
          wndspeed_3_08,...
          wndspeed_4_08,...
          wndspeed_5_08,...
          wndspeed_6_08,...
          wndspeed_7_08,...
          wndspeed_8_08,...
          wndspeed_9_08,...
          wndspeed_10_08,...
          wndspeed_11_08,...
          wndspeed_12_08,...
          wndspeed_1_09,...
          wndspeed_2_09,...
          wndspeed_3_09,...
          wndspeed_4_09,...
          wndspeed_5_09,...
          wndspeed_6_09,...
          wndspeed_7_09,...
          wndspeed_8_09,...
          wndspeed_9_09,...
          wndspeed_10_09,...
          wndspeed_11_09,...
          wndspeed_12_09,...
          wndspeed_1_10,...
          wndspeed_2_10,...
          wndspeed_3_10,...
          wndspeed_4_10,...
          wndspeed_5_10,...
          wndspeed_6_10,...
          wndspeed_7_10,...
          wndspeed_8_10,...
          wndspeed_9_10,...
          wndspeed_10_10,...
          wndspeed_11_10,...
          wndspeed_12_10,...
          wndspeed_1_11,...
          wndspeed_2_11,...
          wndspeed_3_11,...
          wndspeed_4_11,...
          wndspeed_5_11,...
          wndspeed_6_11,...
          wndspeed_7_11,...
          wndspeed_8_11,...
          wndspeed_9_11,...
          wndspeed_10_11,...
          wndspeed_11_11,...
          wndspeed_12_11,...
          wndspeed_1_12,...
          wndspeed_2_12,...
          wndspeed_3_12,...
          wndspeed_4_12,...
          wndspeed_5_12,...
          wndspeed_6_12,...
          wndspeed_7_12,...
          wndspeed_8_12,...
          wndspeed_9_12,...
          wndspeed_10_12,...
          wndspeed_11_12,...
          wndspeed_12_12,...
          wndspeed_1_13,...
          wndspeed_2_13,...
          wndspeed_3_13,...
          wndspeed_4_13,...
          wndspeed_5_13,...
          wndspeed_6_13,...
          wndspeed_7_13,...
          wndspeed_8_13,...
          wndspeed_9_13,...
          wndspeed_10_13,...
          wndspeed_11_13,...
          wndspeed_12_13,...
          wndspeed_1_14,...
          wndspeed_2_14,...
          wndspeed_3_14,...
          wndspeed_4_14,...
          wndspeed_5_14,...
          wndspeed_6_14,...
          wndspeed_7_14,...
          wndspeed_8_14,...
          wndspeed_9_14,...
          wndspeed_10_14,...
          wndspeed_11_14,...
          wndspeed_12_14] = Love_Matthew_get_monthly_windspeeds(filename,iminsamp)
fprintf('Now processing 2005 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_05,wnddir,pres,temp] = RdNCDCData(filename,1,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_05,wnddir,pres,temp] = RdNCDCData(filename,2,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_05,wnddir,pres,temp] = RdNCDCData(filename,3,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_05,wnddir,pres,temp] = RdNCDCData(filename,4,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_05,wnddir,pres,temp] = RdNCDCData(filename,5,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_05,wnddir,pres,temp] = RdNCDCData(filename,6,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_05,wnddir,pres,temp] = RdNCDCData(filename,7,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_05,wnddir,pres,temp] = RdNCDCData(filename,8,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_05,wnddir,pres,temp] = RdNCDCData(filename,9,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_05,wnddir,pres,temp] = RdNCDCData(filename,10,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_05,wnddir,pres,temp] = RdNCDCData(filename,11,2005,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_05,wnddir,pres,temp] = RdNCDCData(filename,12,2005,iminsamp);
fprintf('Processed 2005 data, now processing 2006 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_06,wnddir,pres,temp] = RdNCDCData(filename,1,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_06,wnddir,pres,temp] = RdNCDCData(filename,2,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_06,wnddir,pres,temp] = RdNCDCData(filename,3,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_06,wnddir,pres,temp] = RdNCDCData(filename,4,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_06,wnddir,pres,temp] = RdNCDCData(filename,5,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_06,wnddir,pres,temp] = RdNCDCData(filename,6,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_06,wnddir,pres,temp] = RdNCDCData(filename,7,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_06,wnddir,pres,temp] = RdNCDCData(filename,8,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_06,wnddir,pres,temp] = RdNCDCData(filename,9,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_06,wnddir,pres,temp] = RdNCDCData(filename,10,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_06,wnddir,pres,temp] = RdNCDCData(filename,11,2006,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_06,wnddir,pres,temp] = RdNCDCData(filename,12,2006,iminsamp);
fprintf('Processed 2006 data, now processing 2007 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_07,wnddir,pres,temp] = RdNCDCData(filename,1,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_07,wnddir,pres,temp] = RdNCDCData(filename,2,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_07,wnddir,pres,temp] = RdNCDCData(filename,3,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_07,wnddir,pres,temp] = RdNCDCData(filename,4,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_07,wnddir,pres,temp] = RdNCDCData(filename,5,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_07,wnddir,pres,temp] = RdNCDCData(filename,6,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_07,wnddir,pres,temp] = RdNCDCData(filename,7,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_07,wnddir,pres,temp] = RdNCDCData(filename,8,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_07,wnddir,pres,temp] = RdNCDCData(filename,9,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_07,wnddir,pres,temp] = RdNCDCData(filename,10,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_07,wnddir,pres,temp] = RdNCDCData(filename,11,2007,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_07,wnddir,pres,temp] = RdNCDCData(filename,12,2007,iminsamp);
fprintf('Processed 2007 data, now processing 2008 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_08,wnddir,pres,temp] = RdNCDCData(filename,1,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_08,wnddir,pres,temp] = RdNCDCData(filename,2,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_08,wnddir,pres,temp] = RdNCDCData(filename,3,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_08,wnddir,pres,temp] = RdNCDCData(filename,4,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_08,wnddir,pres,temp] = RdNCDCData(filename,5,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_08,wnddir,pres,temp] = RdNCDCData(filename,6,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_08,wnddir,pres,temp] = RdNCDCData(filename,7,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_08,wnddir,pres,temp] = RdNCDCData(filename,8,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_08,wnddir,pres,temp] = RdNCDCData(filename,9,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_08,wnddir,pres,temp] = RdNCDCData(filename,10,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_08,wnddir,pres,temp] = RdNCDCData(filename,11,2008,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_08,wnddir,pres,temp] = RdNCDCData(filename,12,2008,iminsamp);
fprintf('Processed 2008 data, now processing 2009 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_09,wnddir,pres,temp] = RdNCDCData(filename,1,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_09,wnddir,pres,temp] = RdNCDCData(filename,2,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_09,wnddir,pres,temp] = RdNCDCData(filename,3,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_09,wnddir,pres,temp] = RdNCDCData(filename,4,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_09,wnddir,pres,temp] = RdNCDCData(filename,5,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_09,wnddir,pres,temp] = RdNCDCData(filename,6,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_09,wnddir,pres,temp] = RdNCDCData(filename,7,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_09,wnddir,pres,temp] = RdNCDCData(filename,8,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_09,wnddir,pres,temp] = RdNCDCData(filename,9,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_09,wnddir,pres,temp] = RdNCDCData(filename,10,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_09,wnddir,pres,temp] = RdNCDCData(filename,11,2009,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_09,wnddir,pres,temp] = RdNCDCData(filename,12,2009,iminsamp);
fprintf('Processed 2009 data, now processing 2010 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_10,wnddir,pres,temp] = RdNCDCData(filename,1,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_10,wnddir,pres,temp] = RdNCDCData(filename,2,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_10,wnddir,pres,temp] = RdNCDCData(filename,3,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_10,wnddir,pres,temp] = RdNCDCData(filename,4,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_10,wnddir,pres,temp] = RdNCDCData(filename,5,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_10,wnddir,pres,temp] = RdNCDCData(filename,6,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_10,wnddir,pres,temp] = RdNCDCData(filename,7,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_10,wnddir,pres,temp] = RdNCDCData(filename,8,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_10,wnddir,pres,temp] = RdNCDCData(filename,9,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_10,wnddir,pres,temp] = RdNCDCData(filename,10,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_10,wnddir,pres,temp] = RdNCDCData(filename,11,2010,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_10,wnddir,pres,temp] = RdNCDCData(filename,12,2010,iminsamp);
fprintf('Processed 2010 data, now processing 2011 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_11,wnddir,pres,temp] = RdNCDCData(filename,1,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_11,wnddir,pres,temp] = RdNCDCData(filename,2,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_11,wnddir,pres,temp] = RdNCDCData(filename,3,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_11,wnddir,pres,temp] = RdNCDCData(filename,4,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_11,wnddir,pres,temp] = RdNCDCData(filename,5,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_11,wnddir,pres,temp] = RdNCDCData(filename,6,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_11,wnddir,pres,temp] = RdNCDCData(filename,7,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_11,wnddir,pres,temp] = RdNCDCData(filename,8,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_11,wnddir,pres,temp] = RdNCDCData(filename,9,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_11,wnddir,pres,temp] = RdNCDCData(filename,10,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_11,wnddir,pres,temp] = RdNCDCData(filename,11,2011,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_11,wnddir,pres,temp] = RdNCDCData(filename,12,2011,iminsamp);
fprintf('Processed 2011 data, now processing 2012 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_12,wnddir,pres,temp] = RdNCDCData(filename,1,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_12,wnddir,pres,temp] = RdNCDCData(filename,2,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_12,wnddir,pres,temp] = RdNCDCData(filename,3,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_12,wnddir,pres,temp] = RdNCDCData(filename,4,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_12,wnddir,pres,temp] = RdNCDCData(filename,5,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_12,wnddir,pres,temp] = RdNCDCData(filename,6,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_12,wnddir,pres,temp] = RdNCDCData(filename,7,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_12,wnddir,pres,temp] = RdNCDCData(filename,8,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_12,wnddir,pres,temp] = RdNCDCData(filename,9,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_12,wnddir,pres,temp] = RdNCDCData(filename,10,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_12,wnddir,pres,temp] = RdNCDCData(filename,11,2012,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_12,wnddir,pres,temp] = RdNCDCData(filename,12,2012,iminsamp);
fprintf('Processed 2012 data, now processing 2013 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_13,wnddir,pres,temp] = RdNCDCData(filename,1,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_13,wnddir,pres,temp] = RdNCDCData(filename,2,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_13,wnddir,pres,temp] = RdNCDCData(filename,3,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_13,wnddir,pres,temp] = RdNCDCData(filename,4,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_13,wnddir,pres,temp] = RdNCDCData(filename,5,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_13,wnddir,pres,temp] = RdNCDCData(filename,6,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_13,wnddir,pres,temp] = RdNCDCData(filename,7,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_13,wnddir,pres,temp] = RdNCDCData(filename,8,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_13,wnddir,pres,temp] = RdNCDCData(filename,9,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_13,wnddir,pres,temp] = RdNCDCData(filename,10,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_13,wnddir,pres,temp] = RdNCDCData(filename,11,2013,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_13,wnddir,pres,temp] = RdNCDCData(filename,12,2013,iminsamp);
fprintf('Processed 2013 data, now processing 2014 data \n')
[dttm,timemin,wnddatenum,wndspeed_1_14,wnddir,pres,temp] = RdNCDCData(filename,1,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_2_14,wnddir,pres,temp] = RdNCDCData(filename,2,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_3_14,wnddir,pres,temp] = RdNCDCData(filename,3,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_4_14,wnddir,pres,temp] = RdNCDCData(filename,4,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_5_14,wnddir,pres,temp] = RdNCDCData(filename,5,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_6_14,wnddir,pres,temp] = RdNCDCData(filename,6,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_7_14,wnddir,pres,temp] = RdNCDCData(filename,7,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_8_14,wnddir,pres,temp] = RdNCDCData(filename,8,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_9_14,wnddir,pres,temp] = RdNCDCData(filename,9,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_10_14,wnddir,pres,temp] = RdNCDCData(filename,10,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_11_14,wnddir,pres,temp] = RdNCDCData(filename,11,2014,iminsamp);
[dttm,timemin,wnddatenum,wndspeed_12_14,wnddir,pres,temp] = RdNCDCData(filename,12,2014,iminsamp);
fprintf('Processed 2014 data \n')